"""Deterministic tool skeleton generator (B2).

Given a small contract dict, this module emits a complete Python ``handler``
function with all structural elements pre-baked:

  - ``def handler(*, ...)`` signature with the declared keyword arguments
  - input validation block
  - try/except wrapper that always returns the AWP standard result shape
  - mandatory ``confidence`` field in the success branch
  - explicit ``# === FILL BODY HERE ===`` marker for the LLM-filled compute step
  - explicit ``# === FILL OUTPUT HERE ===`` marker for the result population

Because the structure is generated by code (not LLM), structural rules
(R17 confidence, output shape, kwargs-only signature, namespace) are
**impossible to violate** by construction. The LLM only fills body holes.

If a contract matches a known pattern_id from ``awp.patterns``, the
pattern's pre-verified skeleton is returned verbatim instead — zero
generation, zero LLM tokens.

If the contract carries an ``archetype_id`` + ``recipe_params``, the
generic archetype skeleton is built from those parameters — also zero
LLM tokens for the body, but more flexible than a fixed pattern.

Contract schema (all fields optional except name + inputs):
    {
        "name":          "namespace.action",
        "description":   "one-line purpose",
        "inputs":        {"arg_name": "type_str", ...},
        "outputs":       ["key1", "key2", ...],
        "pattern_id":    "<id from awp.patterns>"          # shortcut 1
        "archetype_id":  "<id from awp.patterns.ARCHETYPES>",  # shortcut 2
        "recipe_params": {...}                              # required iff archetype_id
    }
"""

from __future__ import annotations

from typing import Any


def _format_signature(inputs: dict[str, str]) -> str:
    if not inputs:
        return "**_"
    parts = [f"{name}" for name in inputs.keys()]
    parts.append("**_")
    return ", ".join(parts)


def _format_input_check(inputs: dict[str, str]) -> str:
    if not inputs:
        return "    # (no required inputs)"
    lines = []
    for name in inputs.keys():
        lines.append(
            f"    if {name} is None:\n"
            f'        return {{"ok": False, "status": 400, "data": {{}}, '
            f'"error": "missing required input: {name}"}}'
        )
    return "\n".join(lines)


def _format_output_dict(outputs: list[str]) -> str:
    keys = list(outputs or [])
    if "confidence" not in keys:
        keys.append("confidence")
    items = []
    for k in keys:
        if k == "confidence":
            items.append('            "confidence": 1.0,')
        else:
            items.append(f'            "{k}": {k}_value,')
    return "\n".join(items)


def generate_skeleton(contract: dict[str, Any]) -> str:
    """Render a typed handler skeleton with body holes from a contract.

    If the contract carries a ``pattern_id`` that resolves in the pattern
    library, the pattern's verified skeleton is returned instead.
    """
    name = contract.get("name", "dynamic.unnamed")
    description = contract.get("description", "Generated tool")
    inputs: dict[str, str] = contract.get("inputs", {}) or {}
    outputs: list[str] = list(contract.get("outputs", []) or [])
    pattern_id = contract.get("pattern_id")
    archetype_id = contract.get("archetype_id")
    recipe_params = contract.get("recipe_params")

    # Pattern shortcut: zero-generation path.
    if pattern_id:
        try:
            from awp.patterns import get_pattern

            pat = get_pattern(pattern_id)
            if pat is not None:
                return pat.skeleton
        except Exception:
            pass

    # Archetype shortcut: parametric, zero-LLM-body path.
    if archetype_id and isinstance(recipe_params, dict):
        try:
            from awp.patterns import get_archetype

            arch = get_archetype(archetype_id)
            if arch is not None:
                # Ensure the archetype sees a 'name' param (it always
                # uses this for the error envelope).
                params = dict(recipe_params)
                params.setdefault("name", name)
                code, _pkgs = arch.build_skeleton(params)
                return code
        except Exception:
            pass

    sig = _format_signature(inputs)
    checks = _format_input_check(inputs)
    output_block = _format_output_dict(outputs)
    out_keys = ", ".join(f"{k}_value" for k in (outputs or [])) or "(no outputs)"
    type_hints = "\n".join(
        f"    #   {n}: {t}" for n, t in inputs.items()
    ) or "    #   (no inputs)"

    skeleton = f'''def handler(*, {sig}):
    """{description}

    Tool: {name}
    Inputs:
{type_hints}
    Outputs to populate: {out_keys}
    """
    # ---- Input validation (generated, do not remove) ----
{checks}

    try:
        # === FILL BODY HERE ===
        # Compute the result. You may import any allowed libraries.
        # Assign each output below to a local variable named "<key>_value".
        # Example: mean_value = float(sum(values) / len(values))
        pass

        # === FILL OUTPUT HERE ===
        return {{
            "ok": True,
            "status": 200,
            "data": {{
{output_block}
            }},
            "error": None,
        }}
    except Exception as exc:
        return {{
            "ok": False,
            "status": 500,
            "data": {{}},
            "error": f"{name} failed: {{exc}}",
        }}
'''
    return skeleton


__all__ = ["generate_skeleton"]
