"""AWP Archetypes — generic, domain-free tool skeletons.

An **archetype** is a parametric tool template. Unlike the legacy
hand-written ``Pattern`` (one frozen skeleton per concrete task), an
archetype represents a *shape of work* and emits a concrete handler
when instantiated with parameters.

The six archetypes here cover the recurring shapes observed in real
delegation-loop runs and — by composition — every realistic task an
AWP workflow has been asked to perform:

    Compute    pure data → data, no IO
    Fetch      external → in-memory (HTTP, file, DB)
    Parse      bytes/text → structured (CSV/JSON/HTML/PDF-extract)
    Transform  structured → structured (filter/aggregate/reshape)
    Render     structured → file artifact (image, document, structured)
    Probe      environment introspection (exists/list/stat/env)

Render is a single archetype with a ``backend`` slot
(``matplotlib_png``, ``reportlab_pdf``, ``markdown``, ``html``,
``json``) so a new output format is a recipe parameter, not a new
archetype.

Each archetype's ``build_skeleton(params)`` returns a complete handler
function source string that satisfies the AWP tool contract:
``{ok, status, data, error}`` with a ``confidence`` key in ``data`` on
success.  The skeleton is intentionally generic — domain knowledge
lives in *recipes* (see ``recipe.py``), never in archetype code.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Callable

# ---------------------------------------------------------------------------
# Core dataclass
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class Archetype:
    """A parametric tool template.

    ``build_skeleton`` and ``build_smoke`` are pure functions of the
    recipe params; identical params MUST produce identical output so
    recipes can be content-addressed deterministically.
    """

    id: str
    description: str
    capability_family: str  # e.g. "fetch" — used by R31 plan-tool-closure
    required_params: tuple[str, ...]
    optional_params: tuple[str, ...] = field(default_factory=tuple)
    # version bumps invalidate every recipe captured against this archetype
    version: int = 1

    # build_skeleton(params) -> (handler_source, packages)
    build_skeleton: Callable[[dict[str, Any]], tuple[str, tuple[str, ...]]] = None  # type: ignore
    # build_smoke(params) -> smoke_snippet (executed in a venv post-instantiation)
    build_smoke: Callable[[dict[str, Any]], str] = None  # type: ignore

    def validate_params(self, params: dict[str, Any]) -> list[str]:
        missing = [p for p in self.required_params if p not in params]
        return [f"missing required param '{p}'" for p in missing]


# ---------------------------------------------------------------------------
# Shared helpers (kept tiny — no domain logic)
# ---------------------------------------------------------------------------

_OK_RETURN = '''        return {
            "ok": True,
            "status": 200,
            "data": _data,
            "error": None,
        }
    except Exception as exc:
        return {
            "ok": False,
            "status": 500,
            "data": {},
            "error": f"{_NAME} failed: {exc}",
        }
'''


def _wrap(name: str, sig: str, body: str, *, imports: str = "") -> str:
    """Wrap a body fragment in the standard AWP handler envelope.

    The body must populate a local dict named ``_data`` (which will be
    returned under ``data`` on success) and may raise — exceptions are
    caught and converted to the standard error shape.
    ``_data`` MUST contain a ``confidence`` key by the time the body
    completes (R17).
    """
    return (
        f'''def handler(*, {sig}):
    """Generated by AWP archetype. Do not hand-edit."""
    _NAME = {name!r}
{imports}
    try:
{body}
{_OK_RETURN}'''
    )


def _signature(params_inputs: dict[str, str]) -> str:
    if not params_inputs:
        return "**_"
    return ", ".join(list(params_inputs.keys()) + ["**_"])


# ---------------------------------------------------------------------------
# 1. Compute — pure data → data
# ---------------------------------------------------------------------------


def _compute_skeleton(params: dict[str, Any]) -> tuple[str, tuple[str, ...]]:
    """Pure-function compute. ``params`` must include:
    - ``name``     : tool fqn
    - ``inputs``   : dict[str, str]  declared input names → type hints
    - ``expression``: a Python statement block that assigns to ``_data``
                     (and must include ``_data['confidence']``).
    - ``packages`` : tuple of pip packages required (default ())
    """
    name = params["name"]
    inputs = params.get("inputs", {}) or {}
    expression = params["expression"]
    packages = tuple(params.get("packages", ()) or ())
    sig = _signature(inputs)
    body_indented = "\n".join("        " + line for line in expression.splitlines())
    body = "        _data = {}\n" + body_indented
    return _wrap(name, sig, body), packages


def _compute_smoke(params: dict[str, Any]) -> str:
    sample = params.get("smoke_input", {})
    args = ", ".join(f"{k}={v!r}" for k, v in sample.items())
    return f'''
result = handler({args})
assert result["ok"] is True, f"compute smoke failed: {{result}}"
assert "confidence" in result["data"], "missing confidence (R17)"
print("ARCHETYPE_OK compute")
'''


COMPUTE = Archetype(
    id="compute",
    description="Pure in-memory compute: data → data, no IO.",
    capability_family="compute",
    required_params=("name", "expression"),
    optional_params=("inputs", "packages", "smoke_input"),
    build_skeleton=_compute_skeleton,
    build_smoke=_compute_smoke,
)


# ---------------------------------------------------------------------------
# 2. Fetch — external source → in-memory bytes/json
# ---------------------------------------------------------------------------


def _fetch_skeleton(params: dict[str, Any]) -> tuple[str, tuple[str, ...]]:
    """Fetch from a remote/local source.

    Params:
      - ``name``         : tool fqn
      - ``backend``      : "http_get" | "http_post" | "file_read"
      - ``url_template`` : str (for http_*)  — supports {kw} placeholders
      - ``path_template``: str (for file_read)
      - ``inputs``       : dict[str, str]  caller-supplied kwargs
      - ``timeout``      : int seconds (http only, default 20)
      - ``post_process`` : optional Python snippet operating on ``_raw``,
                            must populate ``_data`` and ``_data['confidence']``.
                            Used to encode source-specific quirks (e.g.
                            CoinGecko 4h candles → daily aggregation).
    """
    name = params["name"]
    backend = params["backend"]
    inputs = params.get("inputs", {}) or {}
    timeout = int(params.get("timeout", 20))
    post = params.get("post_process") or "_data = {'raw': _raw, 'confidence': 1.0}"
    sig = _signature(inputs)

    if backend in ("http_get", "http_post"):
        url_tpl = params["url_template"]
        method = "get" if backend == "http_get" else "post"
        body = f'''        import requests
        _url = f{url_tpl!r}
        _resp = requests.{method}(_url, timeout={timeout})
        if _resp.status_code != 200:
            return {{"ok": False, "status": _resp.status_code, "data": {{}},
                     "error": f"HTTP {{_resp.status_code}}: {{_resp.text[:200]}}"}}
        try:
            _raw = _resp.json()
        except Exception:
            _raw = _resp.text
'''
        body += "\n".join("        " + l for l in post.splitlines())
        return _wrap(name, sig, body), ("requests",)

    if backend == "file_read":
        path_tpl = params["path_template"]
        body = f'''        _path = f{path_tpl!r}
        with open(_path, "rb") as _fh:
            _raw = _fh.read()
'''
        body += "\n".join("        " + l for l in post.splitlines())
        return _wrap(name, sig, body), ()

    raise ValueError(f"fetch: unknown backend {backend!r}")


def _fetch_smoke(params: dict[str, Any]) -> str:
    # Fetch smoke is recipe-supplied (network-mocking is recipe-specific)
    return params.get("smoke_test", 'print("ARCHETYPE_OK fetch (no smoke supplied)")')


FETCH = Archetype(
    id="fetch",
    description="Read from an external source (HTTP, file, …) into memory.",
    capability_family="fetch",
    required_params=("name", "backend"),
    optional_params=("url_template", "path_template", "inputs", "timeout",
                     "post_process", "smoke_test"),
    build_skeleton=_fetch_skeleton,
    build_smoke=_fetch_smoke,
)


# ---------------------------------------------------------------------------
# 3. Parse — bytes/text → structured
# ---------------------------------------------------------------------------


def _parse_skeleton(params: dict[str, Any]) -> tuple[str, tuple[str, ...]]:
    """Parse bytes/text into a structured form.

    Params:
      - ``name``    : tool fqn
      - ``decoder`` : "csv" | "json" | "html" | "custom"
      - ``inputs``  : dict[str, str]  (must include the source kwarg)
      - ``source``  : kwarg name carrying the raw bytes/text/path
      - ``custom_body`` : Python snippet for decoder=="custom"
      - ``packages``: tuple
    """
    name = params["name"]
    decoder = params["decoder"]
    inputs = params.get("inputs", {}) or {}
    source = params["source"]
    sig = _signature(inputs)
    pkgs: tuple[str, ...] = ()

    if decoder == "csv":
        pkgs = ("pandas",)
        body = f'''        import pandas as pd
        _df = pd.read_csv({source})
        _data = {{
            "rows": int(_df.shape[0]),
            "cols": int(_df.shape[1]),
            "columns": list(map(str, _df.columns)),
            "records": _df.to_dict(orient="records"),
            "confidence": 1.0,
        }}
'''
    elif decoder == "json":
        body = f'''        import json
        _src = {source}
        if isinstance(_src, (bytes, bytearray)):
            _src = _src.decode("utf-8")
        if isinstance(_src, str) and _src.lstrip().startswith(("{{", "[")):
            _data = {{"value": json.loads(_src), "confidence": 1.0}}
        else:
            with open(_src, "r", encoding="utf-8") as _fh:
                _data = {{"value": json.load(_fh), "confidence": 1.0}}
'''
    elif decoder == "html":
        pkgs = ("beautifulsoup4",)
        body = f'''        from bs4 import BeautifulSoup
        _soup = BeautifulSoup({source}, "html.parser")
        _data = {{
            "title": (_soup.title.string if _soup.title else ""),
            "text": _soup.get_text(" ", strip=True),
            "links": [a.get("href") for a in _soup.find_all("a") if a.get("href")],
            "confidence": 1.0,
        }}
'''
    elif decoder == "custom":
        custom = params["custom_body"]
        pkgs = tuple(params.get("packages", ()) or ())
        body = "\n".join("        " + l for l in custom.splitlines())
    else:
        raise ValueError(f"parse: unknown decoder {decoder!r}")

    return _wrap(name, sig, body), pkgs


def _parse_smoke(params: dict[str, Any]) -> str:
    return params.get("smoke_test", 'print("ARCHETYPE_OK parse (no smoke supplied)")')


PARSE = Archetype(
    id="parse",
    description="Decode bytes/text into a structured representation.",
    capability_family="parse",
    required_params=("name", "decoder", "source"),
    optional_params=("inputs", "custom_body", "packages", "smoke_test"),
    build_skeleton=_parse_skeleton,
    build_smoke=_parse_smoke,
)


# ---------------------------------------------------------------------------
# 4. Transform — structured → structured
# ---------------------------------------------------------------------------


def _transform_skeleton(params: dict[str, Any]) -> tuple[str, tuple[str, ...]]:
    """Generic structured-data transform.

    Params:
      - ``name``     : tool fqn
      - ``inputs``   : dict[str, str]
      - ``op_chain`` : Python snippet that reads kwargs, populates ``_data``
                       (must include ``_data['confidence']``)
      - ``packages`` : tuple
    """
    name = params["name"]
    inputs = params.get("inputs", {}) or {}
    op = params["op_chain"]
    pkgs = tuple(params.get("packages", ()) or ())
    sig = _signature(inputs)
    body = "        _data = {}\n" + "\n".join("        " + l for l in op.splitlines())
    return _wrap(name, sig, body), pkgs


def _transform_smoke(params: dict[str, Any]) -> str:
    return params.get("smoke_test", 'print("ARCHETYPE_OK transform (no smoke supplied)")')


TRANSFORM = Archetype(
    id="transform",
    description="Reshape, filter, aggregate or join structured data.",
    capability_family="transform",
    required_params=("name", "op_chain"),
    optional_params=("inputs", "packages", "smoke_test"),
    build_skeleton=_transform_skeleton,
    build_smoke=_transform_smoke,
)


# ---------------------------------------------------------------------------
# 5. Render — structured → file artifact (backend slot)
# ---------------------------------------------------------------------------


def _render_skeleton(params: dict[str, Any]) -> tuple[str, tuple[str, ...]]:
    """Render structured data to a file.

    Params:
      - ``name``    : tool fqn
      - ``backend`` : "matplotlib_png" | "reportlab_pdf" | "markdown" |
                       "html" | "json"
      - ``inputs``  : dict[str, str] (must include 'path' or equivalent)
      - ``layout``  : backend-specific Python snippet that, given the
                       caller kwargs, produces the artifact at ``path``.
                       Optional for the simple text backends (markdown,
                       json) where a default exists.
    """
    name = params["name"]
    backend = params["backend"]
    inputs = params.get("inputs", {}) or {}
    layout = params.get("layout")
    sig = _signature(inputs)
    pkgs: tuple[str, ...] = ()

    if backend == "matplotlib_png":
        pkgs = ("matplotlib",)
        if not layout:
            raise ValueError("render(matplotlib_png) requires a 'layout' snippet")
        body = '''        import matplotlib
        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        import os
'''
        body += "\n".join("        " + l for l in layout.splitlines())
        body += '''
        _size = os.path.getsize(path)
        if _size < 1000:
            return {"ok": False, "status": 500,
                    "data": {"path": path, "size_bytes": int(_size)},
                    "error": f"PNG suspiciously small ({_size} bytes)"}
        _data = {"path": path, "size_bytes": int(_size), "confidence": 1.0}
'''
    elif backend == "reportlab_pdf":
        pkgs = ("reportlab",)
        if not layout:
            raise ValueError("render(reportlab_pdf) requires a 'layout' snippet")
        body = '''        from reportlab.lib.pagesizes import letter
        from reportlab.pdfgen import canvas
        import os
        _c = canvas.Canvas(path, pagesize=letter)
'''
        body += "\n".join("        " + l for l in layout.splitlines())
        body += '''
        _c.save()
        _size = os.path.getsize(path)
        _data = {"path": path, "size_bytes": int(_size), "confidence": 1.0}
'''
    elif backend == "markdown":
        body = '''        import os
        _lines = []
'''
        if layout:
            body += "\n".join("        " + l for l in layout.splitlines())
        else:
            body += '''        _lines.append(f"# {title}")
        _lines.append("")
        if isinstance(body, str):
            _lines.append(body)
'''
        body += '''
        _text = "\\n".join(_lines) + "\\n"
        with open(path, "w", encoding="utf-8") as _fh:
            _fh.write(_text)
        _size = os.path.getsize(path)
        _data = {"path": path, "size_bytes": int(_size), "confidence": 1.0}
'''
    elif backend == "html":
        body = '''        import os
        _html = ""
'''
        if layout:
            body += "\n".join("        " + l for l in layout.splitlines())
        else:
            body += '''        _html = f"<!doctype html><html><head><title>{title}</title></head><body>{body}</body></html>"
'''
        body += '''
        with open(path, "w", encoding="utf-8") as _fh:
            _fh.write(_html)
        _size = os.path.getsize(path)
        _data = {"path": path, "size_bytes": int(_size), "confidence": 1.0}
'''
    elif backend == "json":
        body = '''        import json, os
        with open(path, "w", encoding="utf-8") as _fh:
            json.dump(value, _fh, indent=2, default=str)
        _size = os.path.getsize(path)
        _data = {"path": path, "size_bytes": int(_size), "confidence": 1.0}
'''
    else:
        raise ValueError(f"render: unknown backend {backend!r}")

    return _wrap(name, sig, body), pkgs


def _render_smoke(params: dict[str, Any]) -> str:
    return params.get("smoke_test", 'print("ARCHETYPE_OK render (no smoke supplied)")')


RENDER = Archetype(
    id="render",
    description="Render structured data to a file artifact (image / document / structured).",
    capability_family="render",
    required_params=("name", "backend"),
    optional_params=("inputs", "layout", "smoke_test"),
    build_skeleton=_render_skeleton,
    build_smoke=_render_smoke,
)


# ---------------------------------------------------------------------------
# 6. Probe — environment introspection
# ---------------------------------------------------------------------------


def _probe_skeleton(params: dict[str, Any]) -> tuple[str, tuple[str, ...]]:
    """Inspect the local environment.

    Params:
      - ``name`` : tool fqn
      - ``query``: "exists" | "list_dir" | "stat" | "env_var"
      - ``inputs``: dict[str, str]
    """
    name = params["name"]
    query = params["query"]
    inputs = params.get("inputs", {}) or {}
    sig = _signature(inputs)

    if query == "exists":
        body = '''        import os
        _data = {"exists": os.path.exists(path), "confidence": 1.0}
'''
    elif query == "list_dir":
        body = '''        import os
        _entries = sorted(os.listdir(path)) if os.path.isdir(path) else []
        _data = {"entries": _entries, "count": len(_entries), "confidence": 1.0}
'''
    elif query == "stat":
        body = '''        import os
        _st = os.stat(path)
        _data = {"size": int(_st.st_size), "mtime": float(_st.st_mtime), "confidence": 1.0}
'''
    elif query == "env_var":
        body = '''        import os
        _data = {"value": os.environ.get(name_), "present": name_ in os.environ, "confidence": 1.0}
'''
    else:
        raise ValueError(f"probe: unknown query {query!r}")

    return _wrap(name, sig, body), ()


def _probe_smoke(params: dict[str, Any]) -> str:
    return params.get("smoke_test", 'print("ARCHETYPE_OK probe (no smoke supplied)")')


PROBE = Archetype(
    id="probe",
    description="Introspect the local environment (exists / list / stat / env).",
    capability_family="probe",
    required_params=("name", "query"),
    optional_params=("inputs", "smoke_test"),
    build_skeleton=_probe_skeleton,
    build_smoke=_probe_smoke,
)


# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------

ARCHETYPES: dict[str, Archetype] = {
    a.id: a for a in (COMPUTE, FETCH, PARSE, TRANSFORM, RENDER, PROBE)
}


def get_archetype(archetype_id: str) -> Archetype | None:
    return ARCHETYPES.get(archetype_id)


def list_archetypes() -> list[Archetype]:
    return list(ARCHETYPES.values())


def archetype_capability_families() -> set[str]:
    """Capability families covered by the archetype set.

    Used by R31 plan-tool-closure: any subtask whose capability tag
    falls into one of these families is *structurally planable* even
    if no concrete recipe exists yet — the runtime can synthesise one.
    """
    return {a.capability_family for a in ARCHETYPES.values()}


def render_archetype_index() -> str:
    """Compact human-readable archetype table for the manager prompt."""
    lines = ["| archetype | family | required params | description |",
             "|---|---|---|---|"]
    for a in list_archetypes():
        req = ", ".join(a.required_params)
        lines.append(f"| `{a.id}` | `{a.capability_family}` | {req} | {a.description} |")
    return "\n".join(lines)


__all__ = [
    "Archetype",
    "ARCHETYPES",
    "COMPUTE", "FETCH", "PARSE", "TRANSFORM", "RENDER", "PROBE",
    "get_archetype",
    "list_archetypes",
    "archetype_capability_families",
    "render_archetype_index",
]
